//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nutripocket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANM_DADOSGERAIS
    {
        public ANM_DADOSGERAIS()
        {
            this.PACIENTE_CONSULTA = new HashSet<PACIENTE_CONSULTA>();
        }
    
        public int ID_DADOSGERAIS { get; set; }
        public int ID_PACIENTE { get; set; }
        public string MASTIGACAO { get; set; }
        public string DENTICAO { get; set; }
        public string ALERGIA { get; set; }
        public string AVERSOES { get; set; }
        public string ALM_PREFERIDOS { get; set; }
        public string TP_ACUCAR { get; set; }
        public string OUTROS_ACUCAR { get; set; }
        public string HR_MAIS_FOME { get; set; }
        public string TABAGISMO { get; set; }
        public string ETILISMO { get; set; }
        public string FARMACOS { get; set; }
        public string ATVD_FISICA { get; set; }
        public string FREQ_ATVD_FISICA { get; set; }
        public string ING_HIDRICA { get; set; }
        public string HAB_INTESTINAL { get; set; }
        public string ESCALA_BRISTOL { get; set; }
        public string TRATAMENTOS { get; set; }
        public string PROB_TRATAMENTO { get; set; }
        public string TEMPERAMENTO { get; set; }
        public string HR_SONO { get; set; }
        public string CON_TRABALHO { get; set; }
    
        public virtual PACIENTE PACIENTE { get; set; }
        public virtual ICollection<PACIENTE_CONSULTA> PACIENTE_CONSULTA { get; set; }
    }
}
