//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nutripocket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANM_CLINICA
    {
        public ANM_CLINICA()
        {
            this.PACIENTE_CONSULTA = new HashSet<PACIENTE_CONSULTA>();
        }
    
        public int ID_CLINICA { get; set; }
        public int ID_PACIENTE { get; set; }
        public string DISFAGIA { get; set; }
        public string CONSTIPACAO { get; set; }
        public string VOMITOS { get; set; }
        public string ANOREXIA { get; set; }
        public string H_PILORI { get; set; }
        public string PIROSE { get; set; }
        public string ODINOFAGIA { get; set; }
        public string DIARREIA { get; set; }
        public string FLATULENCIA { get; set; }
        public string NAUSEAS { get; set; }
        public string PROB_RESP { get; set; }
        public string GRIPES { get; set; }
        public string HEPS { get; set; }
        public string AFTA { get; set; }
        public string FADIGA { get; set; }
        public string VISAO_BORRADA { get; set; }
        public string DORES_ARTICULACAO { get; set; }
        public string MUDANCA_HUMOR { get; set; }
    
        public virtual PACIENTE PACIENTE { get; set; }
        public virtual ICollection<PACIENTE_CONSULTA> PACIENTE_CONSULTA { get; set; }
    }
}
