//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nutripocket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANTECEDENTES_FAMILIARES
    {
        public ANTECEDENTES_FAMILIARES()
        {
            this.PACIENTE_CONSULTA = new HashSet<PACIENTE_CONSULTA>();
        }
    
        public int ID_ANTECEDENTES { get; set; }
        public int ID_PACIENTE { get; set; }
        public string HIPERTENSAO { get; set; }
        public string OBESIDADE { get; set; }
        public string CANCER { get; set; }
        public string DIABETES { get; set; }
        public string DCV { get; set; }
        public string DISLIPIDEMIA { get; set; }
        public string AVC { get; set; }
        public string ANEMIA { get; set; }
        public string OUTROS { get; set; }
    
        public virtual PACIENTE PACIENTE { get; set; }
        public virtual ICollection<PACIENTE_CONSULTA> PACIENTE_CONSULTA { get; set; }
    }
}
