//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nutripocket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANTROPOMETRIA
    {
        public ANTROPOMETRIA()
        {
            this.PACIENTE_CONSULTA = new HashSet<PACIENTE_CONSULTA>();
        }
    
        public int ID_ANTRO { get; set; }
        public int ID_PACIENTE { get; set; }
        public string PESO_ATUAL { get; set; }
        public string PESO_HABITUAL { get; set; }
        public string PORC_ADEQUADO { get; set; }
        public string ALTURA { get; set; }
        public string IMC { get; set; }
        public string CLASSIFICACAO { get; set; }
    
        public virtual PACIENTE PACIENTE { get; set; }
        public virtual ICollection<PACIENTE_CONSULTA> PACIENTE_CONSULTA { get; set; }
    }
}
