//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nutripocket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EX_LABORA
    {
        public EX_LABORA()
        {
            this.PACIENTE_CONSULTA = new HashSet<PACIENTE_CONSULTA>();
        }
    
        public int ID_EX_LABORA { get; set; }
        public int ID_PACIENTE { get; set; }
        public string HERMOGRAMA { get; set; }
        public string TRIGLICERIDIOS { get; set; }
        public string PRESSAO_ARTERIAL { get; set; }
        public string GLICEMIA { get; set; }
        public string COLESTEROL { get; set; }
        public string PARASITOLOGICO { get; set; }
        public string CORTISOL { get; set; }
        public string OUTROS { get; set; }
    
        public virtual PACIENTE PACIENTE { get; set; }
        public virtual ICollection<PACIENTE_CONSULTA> PACIENTE_CONSULTA { get; set; }
    }
}
