//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nutripocket.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NutriPocketEntities : DbContext
    {
        public NutriPocketEntities()
            : base("name=NutriPocketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ANM_CLINICA> ANM_CLINICA { get; set; }
        public virtual DbSet<ANM_DADOSGERAIS> ANM_DADOSGERAIS { get; set; }
        public virtual DbSet<ANTECEDENTES_FAMILIARES> ANTECEDENTES_FAMILIARES { get; set; }
        public virtual DbSet<ANTROPOMETRIA> ANTROPOMETRIA { get; set; }
        public virtual DbSet<APARENCIA> APARENCIA { get; set; }
        public virtual DbSet<EX_LABORA> EX_LABORA { get; set; }
        public virtual DbSet<FREQ_ALIMENTAR> FREQ_ALIMENTAR { get; set; }
        public virtual DbSet<NUTRICIONISTA> NUTRICIONISTA { get; set; }
        public virtual DbSet<PACIENTE> PACIENTE { get; set; }
        public virtual DbSet<PACIENTE_CONSULTA> PACIENTE_CONSULTA { get; set; }
        public virtual DbSet<PERIODICIDADE> PERIODICIDADE { get; set; }
        public virtual DbSet<RECEITAS> RECEITAS { get; set; }
        public virtual DbSet<RECOR_ALIMENTACAO> RECOR_ALIMENTACAO { get; set; }
    }
}
