//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nutripocket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NUTRICIONISTA
    {
        public int ID_NUTRICIONISTA { get; set; }
        public string NUT_NOME { get; set; }
        public string NUT_SEXO { get; set; }
        public string NUT_EMAIL { get; set; }
        public string NUT_CRN { get; set; }
        public string AREA_ATUACAO { get; set; }
    }
}
