//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nutripocket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACIENTE_CONSULTA
    {
        public string ID_CONSULTA { get; set; }
        public int ID_PACIENTE { get; set; }
        public int ID_ANTRO { get; set; }
        public int ID_ANTECEDENTES { get; set; }
        public int ID_DADOSGERAIS { get; set; }
        public int ID_CLINICA { get; set; }
        public int ID_APARENCIA { get; set; }
        public int ID_EX_LABORA { get; set; }
    
        public virtual ANM_CLINICA ANM_CLINICA { get; set; }
        public virtual ANM_DADOSGERAIS ANM_DADOSGERAIS { get; set; }
        public virtual ANTECEDENTES_FAMILIARES ANTECEDENTES_FAMILIARES { get; set; }
        public virtual ANTROPOMETRIA ANTROPOMETRIA { get; set; }
        public virtual APARENCIA APARENCIA { get; set; }
        public virtual EX_LABORA EX_LABORA { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
    }
}
