//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nutripocket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEITAS
    {
        public int ID_RECEITA { get; set; }
        public string TITULO { get; set; }
        public string CATEGORIA { get; set; }
        public string MODO_PREPARO { get; set; }
        public string INGREDIENTES { get; set; }
        public Nullable<bool> FOTO_RECEITA { get; set; }
        public Nullable<int> ID_PACIENTE { get; set; }
    
        public virtual PACIENTE PACIENTE { get; set; }
    }
}
